### PR TITLE
Add Dark Mode support

### PR DESCRIPTION
**Pull request by TotalCaesar659**

### CODE REVIEW

**Comment by SimonBrazell** [comment]
Thank you for this, I'll have a look at it and likely merge shortly. 

Maybe we should also add light mode support while we are at it? The original colour scheme kinda lends itself more to dark mode I think, never really thought about light mode as I don't use it myself, but might be a nice addition for those that do? 

Much appreciated!

**Comment by TotalCaesar659** [comment]
I've added Light Mode.

**Comment by SimonBrazell** [comment]
Hello I've installed and tested this on my system just now and unfortunately I don't see any difference when switching between light/dark mode on my OS (macOS), are the changes more pronounced on your system?

**Comment by TotalCaesar659** [comment]
Lubuntu 20.04, Firefox 76.0, Light and Dark modes work alright after changing system GTK3 themes.

**Comment by SimonBrazell** [comment]
Looks good, wonder why it doesn't look like that for me...

**Comment by TotalCaesar659** [comment]
I don't have Mac, so I can't help you with that, only merge some changes if they'll be needed.

**Comment by SimonBrazell** [comment]
No worries, I'll have a play around with it and see if I can get it working.

**Comment by SimonBrazell** [comment]
Sorry it may be a few weeks before I get to this, finding it had to make time for this lately...

**Comment by TotalCaesar659** [comment]
It's alright, I don't hurry.

**Comment by B0pol** [comment]
Maybe it's because your browser sets `no-preference` instead of `light`?

[prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) has three values: no-preference, light and dark.

**Comment by SimonBrazell** [comment]
Thanks @B0pol, I got it working, it was indeed the `prefers-color-scheme` overridden by the browser. 

I'm going to tweak a few things and release this on AMO shortly.

Cheers @TotalCaesar659! 🙂

**Comment by TotalCaesar659** [comment]
Thank you vary much, @SimonBrazell!

**Pull request merged**
