### PR TITLE
Added Change Instance button to address-bar

### PR DESCRIPTION
**Pull request by ManeraKai**
An instance may be slow, not working, language isn't English, and many other things that will let you want to change to another one. Just click on that button in the address bar, and as you wish.

### CODE REVIEW

**Comment by alefvanoon** [comment]
@ManeraKai thanks for your PR.
Did you test this code on a chromium based browser?
https://developer.chrome.com/docs/extensions/mv3/intro/

**Comment by ManeraKai** [comment]
@alefvanoon I didn't. Did you face any problems?

**Comment by alefvanoon** [comment]
> @alefvanoon I didn't. Did you face any problems?

Yes, manifest problem.
Failed to load extension
File
/mnt/shampoo/dev/privacy/web-ext-artifacts/privacy_redirect-1.1.49
Error
Only one of 'browser_action', 'page_action', and 'app' can be specified.
Could not load manifest.

**Comment by SimonBrazell** [comment]
Hi guys thanks for your contributions, I'm in the midst of a large project at work and so have been drained of enthusiasm for programming projects after hours lately, so no time to dedicate to this extension unfortunately...

Just wanted to chime in here, from my investigations it seems that the manifest V3 scheme will ruin this extension (and many other important ones like uBlock Origin...) as Google is removing the blocking version of the webRequest API, which this extension makes heavy use of. I'm not sure what Mozilla plans to do, need to look into that, but if they follow Google then this extension will be dead. If instead they continue to support V2 manifests then this extension will be Firefox only going forward. 

Google have stated recently that they will no longer accept new V2 extension submission from 17th January 2022.

**Comment by alefvanoon** [comment]
> Hi guys thanks for your contributions, I'm in the midst of a large project at work and so have been drained of enthusiasm for programming projects after hours lately, so no time to dedicate to this extension unfortunately...

Hey @SimonBrazell 
We created a fork so that if you want to discontinue the project it lives as it is very useful to us. We would love to be mentioned in readme as the new repository 
We are already merging new useful pr’s and add the feature for checking online instances.
https://github.com/libredirect/libredirect

**Comment by SimonBrazell** [comment]
@ManeraKai I'm encountering the same problem that @alefvanoon mentioned, can't load the extension in Chrome due to issues with the manifest file, it works in Firefox but seems to remove the popup?

**Comment by ManeraKai** [comment]
@SimonBrazell The popup is working for me. Do you mean this popup?
image

**Comment by SimonBrazell** [comment]
Yeah that's the one, I added your branch to my local firefox install last night and could only see the icon in the address bar, also any changes would also need to support Chrome, did you look into the manifest issue noted above?

**Comment by SimonBrazell** [comment]
> We created a fork so that if you want to discontinue the project it lives as it is very useful to us. We would love to be mentioned in readme as the new repository
> We are already merging new useful pr’s and add the feature for checking online instances.

@alefvanoon I'd prefer it if others offered to help maintain this project before starting another one, PR is not dead just development has slowed down as it's just me working on it and I lack time lately.

**Comment by ManeraKai** [comment]
> did you look into the manifest issue noted above?

I looked at it and seemed as a restriction to prevent cluttering. I think the only way is using a separate extension.

**Pull request closed without merging**
