### PR TITLE
Enable SimplyTranslate by default

### PR DESCRIPTION
**Pull request by fattalion**
I personally think that the redirection works pretty well, but feel free to delay/not merge this PR at all if so you wish.

Also, a minor note: I think SimplyTranslate should be moved above "Search Engines", which I find a more logical order. Thoughts?

### CODE REVIEW

**Comment by SimonBrazell** [comment]
This worries me a little, annoyed a fair few people last time I enabled a new redirect by default (search engines), promised to never do it again at the time 🙂

**Comment by fattalion** [comment]
No worries, I wouldn't mind keeping it disabled by default. Could we at least remove the "New" badge?

**Comment by SimonBrazell** [comment]
Yeah sure I can do that, no worries, I really should add some sort of popup or something that is displayed on update to tell people about changes in each release, perhaps I'll start that with the next release.

**Comment by fattalion** [comment]
Thanks for doing this; I just kept delaying it forever. :P

**Pull request closed without merging**
