### PR TITLE
Add Russian translation

### PR DESCRIPTION
**Pull request by TotalCaesar659**

### CODE REVIEW

**Comment by SimonBrazell** [comment]
Thanks @TotalCaesar659 did you want to provide a store translation also? I added a French translation to both stores last night.

**Comment by TotalCaesar659** [comment]
What does it mean: "store translation"?

**Comment by SimonBrazell** [comment]
Sorry should have explained myself a bit better, I was referring to the AMO and Chrome webstore listings for the extension, I think I'll add the fields as messages to the locale files so that this gets captured in the repo also.

**Comment by TotalCaesar659** [comment]
Ah, I got it. If you add them in locale files, I'll update it.

**Comment by SimonBrazell** [comment]
Just added this [_locales/ru/store.md](https://github.com/SimonBrazell/privacy-redirect/blob/master/_locales/ru/store.md#extension-store-amo--chrome-web-store-listing) which contains the `Summary` and `Description` that is currently displayed on the store pages. 

I wanted to include them in the `messages.json` file also but formatting is important, particularly newlines, which I couldn't do in JSON so made a separate MD file for each locale instead.

**Comment by TotalCaesar659** [comment]
[Done](https://github.com/SimonBrazell/privacy-redirect/pull/77).

**Comment by SimonBrazell** [comment]
Good stuff! I've added it to AMO.

**Pull request merged**
