### PR TITLE
Add Search Engine redirects.

### PR DESCRIPTION
**Pull request by aapl-yumi**
Choosing instances for Search Engine redirects are still not available, therefore, redirects are done to random Search Engines. #16

### CODE REVIEW

**Comment by SimonBrazell** [comment]
Thanks heaps @aapl-yumi great job! I'll try this out on my machine and fill in any gaps.

**Comment by SimonBrazell** [comment]
`notPrivateSearchEngine.includes(url.host)` will likely catch far more requests than is intended, should use a regex instead that includes the query so that we only catch search requests.

**Comment by aapl-yumi** [comment]
What does that mean? I understand the part of only querying the search requests. But I don't understand what regex is.

**Comment by SimonBrazell** [comment]
Hi @aapl-yumi sorry should have been more clear, I meant regular expression, so rather than catch the Google search requests looking for the presence of the target domains e.g. `notPrivateSearchEngine.includes(url.host)` as those domains are also used for other applications, we should perhaps instead use a regular expression, like what was done with the OSM redirects: `const googleMapsRegex = /https?:\/\/(((www|maps)\.)?(google\.).*(\/maps)|maps\.(google\.).*)/;`

**Comment by SimonBrazell** [comment]
Just worried we might accidentally redirect something we don't want to redirect using the current method, do you think that's likely?

**Comment by aapl-yumi** [comment]
Thank you for making it clear. I will do it!

**Comment by aapl-yumi** [comment]
I have tried to make the regex work on my extension, and it worked which can be checked in [version 0.0.7](https://github.com/bluelockorg/Blue-Privacy-Extension/commit/9b4245ed17bf2fa3a067597b8adf4bd3e0fa3e7f). However, when I try to just copy and paste the same code I added on my extension to Privacy-Redirect, redirection doesn't work. Would you mind checking why this may be? I'm sorry, I am just a beginner in developing extension, which may have or not have been obvious.

**Comment by SimonBrazell** [comment]
Thanks @aapl-yumi I'll have a look and let you know what the issue is when I get a chance. 

For future reference you can view the javascript console of the background script in Firefox by visiting the extensions debugging page - `about:debugging#/runtime/this-firefox`, and clicking the `Inspect` button for the relevant extension, this will allow you to pinpoint errors that occur in the background script, usually pointing to the line of code that the problem is occurring at. 

There is a similar feature in Chromium via the Extensions page - `chrome://extensions/`, you need to enable `Developer mode` first and then you can see the `Inspect views background page` link for each extension you have installed which will open up the console / DevTools.

**Comment by aapl-yumi** [comment]
Ah yes. I am aware of that, however, I was not able to see any errors, so I needed your help.

**Comment by aapl-yumi** [comment]
@SimonBrazell I was able to make it work. If you could check, please do. Thank you!

**Comment by SimonBrazell** [comment]
Thanks @aapl-yumi sorry I took so long to respond, been busy with other things lately, I'll have a play with it and let you know. Cheers!

**Comment by SimonBrazell** [comment]
It works! 🙂 thanks @aapl-yumi

**Comment by SimonBrazell** [comment]
Oh and I should have mentioned this before I merged... I'm in the process of changing the project license from `MIT License` to the `GNU General Public License v3.0` I hope you are okay with this?

**Comment by SimonBrazell** [comment]
See #130

**Comment by aapl-yumi** [comment]
Yup! It's totally fine. Thanks for letting me know. Also, thank you for merging it!

**Pull request merged**
