### PR TITLE
Grammar fixes

### PR DESCRIPTION
**Pull request by TotalCaesar659**

### CODE REVIEW

**Comment by SimonBrazell** [comment]
Curious why you removed the emojis?

**Comment by TotalCaesar659** [comment]
Oh, I'm very sorry for this. I'm using [special extension](https://github.com/erikdesjardins/no-emoji) for remove them in web pages (they're annoying me), so I even haven't seen them.

**Comment by SimonBrazell** [comment]
Oh right, no worries I just use them to make the description a little more interesting looking, particularly on the Chrome web store which doesn't even allow any HTML elements.

**Comment by TotalCaesar659** [comment]
I [got them back](https://github.com/SimonBrazell/privacy-redirect/pull/80) to Russian translation too.

**Pull request merged**
